services:
  - type: web
    name: food-delivery-app
    runtime: node
    plan: starter
    buildCommand: cd server && npm install && npm run build:server && cd ../front && npm install && npm run build
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URl
        fromDatabase:
          name: mongodb-connection
          property: connectionString
      - key: JWT_TOKEN
        generateValue: true
      - key: CLOUDINAR_NAME
        sync: false
      - key: CLOUDINAR_API_KEY
        sync: false
      - key: CLOUDINAR_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://food-delivery-app.onrender.com
      - key: BACKEND_URL
        value: https://food-delivery-app.onrender.com
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/v1/auth/health
    
databases:
  - name: mongodb-connection
    databaseName: food-app
    user: admin